export const API_ROUTES = {
  USER: {
    REGISTER: "/api/user/auth/register",
    VERIFY_OTP: "/api/user/auth/verify-otp",
    RESEND_OTP: "/api/user/auth/resend-otp",
    LOGIN: "/api/user/auth/login",
    GOOGLE: "/api/user/auth/google",
    FORGOT_PASSWORD: "/api/user/auth/forgot-password",
    VERIFY_RESET_OTP: "/api/user/auth/verify-reset-otp",
    RESET_PASSWORD: "/api/user/auth/reset-password",
    LOGOUT: "/api/user/auth/logout",
    REFRESH_TOKEN: "/api/user/auth/refresh-token",
    DASHBOARD: "/api/user/auth/dashboard",
    MOOD: "/api/user/auth/mood",
    MISSION: (id: string) => `/api/user/auth/missions/${id}`,
    THERAPISTS: "/api/user/auth/therapists",
  },
  THERAPIST: {
    REGISTER: "/api/therapist/auth/register",
    VERIFY_OTP: "/api/therapist/auth/verify-otp",
    RESEND_OTP: "/api/therapist/auth/resend-otp",
    LOGIN: "/api/therapist/auth/login",
    FORGOT_PASSWORD: "/api/therapist/auth/forgot-password",
    VERIFY_RESET_OTP: "/api/therapist/auth/verify-reset-otp",
    RESET_PASSWORD: "/api/therapist/auth/reset-password",
    LOGOUT: "/api/therapist/auth/logout",
    DASHBOARD: "/api/therapist/auth/dashboard",
  },
  ADMIN: {
    LOGIN: "/api/admin/login",
    LOGOUT: "/api/admin/logout",
    USERS: "/api/admin/users",
    USER_STATUS: (id: string) => `/api/admin/users/${id}/status`,
    THERAPISTS: "/api/admin/therapists",
    THERAPIST_STATUS: (id: string) => `/api/admin/therapists/${id}/status`,
  },
} as const;